version: '3'
services:
  web:
    environment:
      - POSTGRES_PASSWORD=diego123
    build: .
    command: /bin/sh init.sh
    volumes:
      - .:/piggisweb
    ports:
      - "3021:3000"
    external_links:
      - postgres_db:postgres
