version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh init.sh
    volumes:
      - .:/piggisweb
    ports:
      - "3021:3000"
    depends_on:
      - db
volumes:
  db:
